### ISSUE TITLE
Representing erroneous nodes

### ISSUE THREAD

**Issue by devnote-dev** [lucid-crystal/compiler#33]
As I was working on #21 I came across various syntactical issues with how Crystal parses certain constructs/expressions, however, this also lead me to uncover (or I guess rediscover?) a deeper issue within Lucid: erroneous nodes. This can be best explained with the newly added alias support which treats `alias bar = foo` as valid.

Error handling is a core part of Lucid, therefore _how we handle error handling is vital_. Initial discussions around this suggested using an error node type that wraps around the offending node. More recent thoughts suggests simply having an `valid?`/`invalid?` property on all nodes (naming isn't really important just yet). I'm wondering how practical the former is, and also if we might lose contextual information with the latter.

**Comment by nobodywasishere** [comment]
For larimar, I have the lexer emit `vt_skipped` tokens for stuff it doesn't understand and the parser emit `vt_missing` if there's a token/node that it's expecting (like end). Both are either wrapped in `AST::Error` node or are a token on a different ndoe. However, this is just for syntactic errors (w/o a message attached to them).

I've been contemplating having one central `ErrorType` string enum to centralize all the syntactic and semantic errors across the lexer/parser/any semantic passes, and then I could have a `error_type` field on each node/token that says what error(s) it has on it. I haven't done experiments tho to see how well that would work though.

**Comment by devnote-dev** [comment]
I'm leaning towards this idea – how do other languages handle this?

**Comment by nobodywasishere** [comment]
Ruby prism has a single config.yml that defines their entire AST, including the possible errors:
https://github.com/ruby/prism/blob/93c0474fbcccd5946e3044973c7d2b2aa10da513/config.yml#L1

The parser errors are attached to the parser as a whole though, instead of individual nodes:
https://github.com/ruby/prism/blob/93c0474fbcccd5946e3044973c7d2b2aa10da513/include/prism/parser.h#L734

I presume this helps with not needing to walk the AST tree in order to get all of the errors.

**Comment by devnote-dev** [comment]
A YAML document of all possible errors sounds like hell...

I think we can make use of parts of the other ideas: using an error type encapsulating the offending node, which is stored as a reference in both the parser and in the parsed syntax tree. That way we can traverse the tree as well as get the errors straight from the parser, depending on the use-case.

**Comment by nobodywasishere** [comment]
Yeah I think they use a YAML file so they can have binding generators for other languages.

How would you handle lexer errors (like a number with a malformed suffix)?

**Comment by devnote-dev** [comment]
I've tried to minimise lexer-based errors. I think that instead of trying to include additional contextual information, we instead just lex it for what it is — i.e. for incorrectly suffixed numbers, we create a specific token kind for that. It will be implicitly treated as an erroneous token by the parser which can then produce the appropriate error node.

String tokens including heredocs (and macro control & embed tokens when they are supported) are the only exceptions to this, as they operate on delimiters which are near to impossible to represent contextually.

**Comment by devnote-dev** [comment]
Upon further testing my concern is growing over syntactical errors which largely comes from the parser, so I think pausing additional coverage contributions to implement error handling now would be a good idea.

**Comment by devnote-dev** [comment]
Small update on error storage: a `Lucid::Parser` instance cannot be acquired so such errors would need to be returned with the nodes, I think this should be fine for a `Program` type which can also be passed to the semantic visitors when we get to that stage.
