### ISSUE TITLE
Precedence-Based Parsing

### ISSUE THREAD

**Issue by devnote-dev** [lucid-crystal/compiler#4]
After some recent experimenting with grouped expressions, it's evident that the parser's current parsing model will not be sustainable in the long run. Precedence-based parsing as seen in other languages would eliminate the issues encountered from this (you can see what they are by running basic grouped expressions in the compiler) as well as provide a clearer differentiation between expressions and statements. Funnily enough, the Crystal compiler doesn't seem to use the precedence model... 🤔

**Comment by nobodywasishere** [comment]
Is this precedence based similar to what's seen in tree sitter?

**Comment by devnote-dev** [comment]
Yes, [Keidax's implementation](https://github.com/keidax/tree-sitter-crystal/blob/73946f8cbf0950fc451459b71993513be89422bb/grammar.js#L140) is what the Crystal Lang Tools tree-sitter is based off, which also follows from the Crystal docs.
